name: test-deploy-document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-deploy-document:
    name: Test Deploy to GitHub Pages
    runs-on: ubuntu-latest
    env:
      working-directory: ./website
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.working-directory }}
      - name: Build website
        run: npm run build
        working-directory: ${{ env.working-directory }}
